version: '3'
services:

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/tweet_collector
    environment:
    - TWITTER_CONSUMER_API_KEY=${TWITTER_CONSUMER_API_KEY}
    - TWITTER_CONSUMER_API_SECRET=${TWITTER_CONSUMER_API_SECRET}
    - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
    - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    depends_on:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - "27017:27017"

  etl_job:
    build: etl_job/
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    depends_on:
    - postgresdb
    - mongodb

  postgresdb:
    image: postgres:10
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    expose:
    - "5432"
    ports:
    - "5432:5432"
