version: '3'
services:
  
  postgresdb:
    container_name: postgres_container
    image: postgres:12.6
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    ports:
    - "5432:5432"
  
  mongodb:
    image: mongo
    ports:
    - "27017:27017"

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/tweet_collector
    environment:
    - API_KEY=${API_KEY}
    - API_SECRET=${API_SECRET}
    depends_on:
    - mongodb

  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/etl_job
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    depends_on:
    - postgresdb
    - mongodb

  # dash:
  #   container_name: dash
  #   build: dash_container
  #   volumes:
  #   - ./dash_container/:/app/
  #   ports:
  #     - 8050:8050
  #   expose:
  #     - 8050
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #   depends_on:
  #     - postgresdb
  #     - mongodb