version: '3'
services:

  tweet_collector:
    build: tweet_collector/
    links:
    - mongodb

  mongodb:
    image: mongo
    ports:
    - "27017:27017"

  etl_job:
    build: etl_job/
    links:
    - mongodb
    - postgresdb

  postgresdb:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD=${PG_PASSWORD}
    expose:
    - "5555"
    ports:
    - "5555:5432"
